// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4IpJp_tQ1RX7WZBJZPBW-CWxvExnRO0',
    appId: '1:314471718804:web:ebadb491849b060ec0b981',
    messagingSenderId: '314471718804',
    projectId: 'saan-jo',
    authDomain: 'saan-jo.firebaseapp.com',
    storageBucket: 'saan-jo.appspot.com',
    measurementId: 'G-9K2J301301',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj4IpJp_tQ1RX7WZBJZPBW-CWxvExnRO0',
    appId: '1:314471718804:android:0adec102e0e1e2ddc0b981',
    messagingSenderId: '314471718804',
    projectId: 'saan-jo',
    storageBucket: 'saan-jo.appspot.com',
  );
}
